included:
  - unicorn
  - unicornTests

excluded:
  - build
  - .github
  - Library

# Some common rule adjustments
disabled_rules:
  - trailing_whitespace # Can be annoying during development
  - line_length         # Sometimes unavoidable in complex logic
  - identifier_name     # Solo dev often uses short names (s1, a1, etc.)

opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - vertical_whitespace_closing_braces

# Customizing existing rules
function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 20
  error: 30
